#!/usr/bin/env ruby

require 'telegram/bot'

require './lib/message_responder'
require './lib/app_configurator'
require 'openssl'

OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

config = AppConfigurator.new

token = config.get_token
logger = config.get_logger

logger.debug 'Starting telegram bot'

message_responder = nil

threads = []
threads << Thread.new {
  Telegram::Bot::Client.run(token) do |bot|
    bot.listen do |message|
      options = {bot: bot, message: message}
      logger.debug "@#{message.from.username}: #{message.text}"
      message_responder ||= MessageResponder.new(options)
      message_responder.message = message
      message_responder.respond
    end
  end
}
threads << Thread.new {
  loop do
    if message_responder
      message_responder.send_message_by_timer
      sleep message_responder.timer_interval
    end
  end
}
threads.map(&:join)
