#!/usr/bin/env ruby

require 'telegram/bot'

require './lib/message_responder'
require './lib/app_configurator'
require 'openssl'

OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

config = AppConfigurator.new

token = ENV['TELEGRAM_BOT_TOKEN'] || config.get_token
logger = config.get_logger

logger.debug 'Starting telegram bot'

message_responder = nil

threads = []
threads << Thread.new do
  Telegram::Bot::Client.run(token) do |bot|
    bot.listen do |message|
      if message.text && message.text.lines.count == 1
        options = { bot: bot, message: message, logger: logger }
        # logger.debug "@#{message.from.username}: #{message.text}"
        message_responder ||= MessageResponder.new(options)
        message_responder.message = message
        message_responder.respond
      end
    end
  end
end
threads << Thread.new do
  loop do
    if message_responder&.parser && message_responder&.start_timer
      message_responder.send_message_by_timer
      sleep message_responder.timer_interval || 5
    end
  end
end
threads.map(&:join)
