#!/usr/bin/env ruby

require 'telegram/bot'

require "#{File.expand_path File.dirname(__FILE__)}/lib/message_responder"
require "#{File.expand_path File.dirname(__FILE__)}/lib/app_configurator"
require 'openssl'

OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

config = AppConfigurator.new
config.configure

token = config.get_token
logger = config.get_logger

logger.debug 'Starting telegram bot'

message_responder = nil

threads = []
threads << Thread.new do
  Telegram::Bot::Client.run(token) do |bot|
    bot.listen do |message|
      if message.text && message.text.lines.count == 1
        options = { bot: bot, message: message, logger: logger }
        message_responder ||= MessageResponder.new(options)
        message_responder.message = message
        begin
          message_responder.respond
        rescue => e
          logger.debug e.message
          logger.debug e.backtrace.inspect
        end
      end
    end
  end
end
threads << Thread.new do
  loop do
    if message_responder&.parser && message_responder&.start_timer
      begin
        message_responder.send_message_by_timer
      rescue => e
        logger.debug e.message
        logger.debug e.backtrace.inspect
      end
      sleep message_responder.timer_interval || 5
    end
  end
end
threads.map(&:join)
