source 'https://rubygems.org'
# gem 'mechanize'
gem 'telegram-bot-ruby'
# gem 'rgeo-shapefile'
gem 'ruby_kml', git: 'git://github.com/VasiliyNovosad/ruby_kml.git'
gem 'activerecord'
gem 'pg'
gem 'rake'