source 'https://rubygems.org'
ruby '2.6.5'

# gem 'mechanize'
gem 'telegram-bot-ruby'
# gem 'rgeo-shapefile'
gem 'ruby_kml', github: 'VasiliyNovosad/ruby_kml'
gem 'gpx'
gem 'activerecord'
gem 'pg'
gem 'rake'
gem 'daemons'