telegram_bot_token: 416219810:AAHXGIdL5QIlkMnGIGE6xfnIK4a0C_NtZDI
# telegram_bot_token(Fr1endBot): 171556746:AAEd8YJrYhFsiLjVEkyIk2cmluEf2lWkA5s
# telegram_bot_token(Fr1endQuestBot): 416219810:AAHXGIdL5QIlkMnGIGE6xfnIK4a0C_NtZDI
users:
  Fr1end: Fr1end_w0lf
  vnovosad: V0rtex