telegram_bot_token: 416219810:AAHXGIdL5QIlkMnGIGE6xfnIK4a0C_NtZDI
personal_chat_id: 84163578
admin_id: 84163578
# telegram_bot_token(Fr1endBot): 171556746:AAEd8YJrYhFsiLjVEkyIk2cmluEf2lWkA5s
# telegram_bot_token(Fr1endQuestBot): 416219810:AAHXGIdL5QIlkMnGIGE6xfnIK4a0C_NtZDI